# Generated by Django 5.0.7 on 2024-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_flair_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='content',
            name='h5p_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(default='Module Assessment', max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image'), ('h5p', 'H5P')], max_length=10),
        ),
    ]
