# Generated by Django 5.0.7 on 2024-08-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_comment_updated_at_content_h5p_url_forum_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='flairs',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='module',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
