# Generated by Django 5.0.7 on 2024-08-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee')], default='Student', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_office_section_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('lived_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Intersex'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('gender_identity', models.CharField(choices=[('Cisgender', 'Cisgender'), ('Transgender', 'Transgender'), ('Agender', 'Agender'), ('Gender Fluid', 'Gender Fluid'), ('Gender Queer', 'Gender Queer')], default='Prefer not to say', max_length=20)),
                ('preferred_pronoun', models.CharField(choices=[('She/Her', 'She/Her'), ('He/Him', 'He/Him'), ('They/Them', 'They/Them')], default='Prefer not to say', max_length=20)),
                ('indigenous_cultural_community', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('differently_abled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('lived_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Intersex'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('gender_identity', models.CharField(choices=[('Cisgender', 'Cisgender'), ('Transgender', 'Transgender'), ('Agender', 'Agender'), ('Gender Fluid', 'Gender Fluid'), ('Gender Queer', 'Gender Queer')], default='Prefer not to say', max_length=20)),
                ('preferred_pronoun', models.CharField(choices=[('She/Her', 'She/Her'), ('He/Him', 'He/Him'), ('They/Them', 'They/Them')], default='Prefer not to say', max_length=20)),
                ('indigenous_cultural_community', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('differently_abled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
