# Generated by Django 5.0.7 on 2024-08-12 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='preferred_pronoun',
            field=models.CharField(choices=[('She/Her', 'She/Her'), ('He/Him', 'He/Him'), ('They/Them', 'They/Them'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.CharField(choices=[('Office of the Executive Vice President', 'Office of the Executive Vice President'), ('Office of the Vice President for Academic Affairs', 'Office of the Vice President for Academic Affairs'), ('Office of the Vice President for Planning and Finance', 'Office of the Vice President for Planning and Finance'), ('Office of the Vice President for Student Affairs and Services', 'Office of the Vicec President for Student Affairs and Services'), ('Office of the Vice President for Administration', 'Office of the Vice President for Administration'), ('Office of the Vice President for Campuses', 'Office of the Vice President for Campuses'), ('Office of the Vice President for Research, Extension, and Development', 'Office of the Vice President for Research, Extension, and Development'), ('Office of the President', 'Office of the President')], default='Prefer not to say', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Intersex', 'Intersex'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, choices=[('CAF', 'College of Accountancy and Finance'), ('CADBE', 'College of Architecture, Design, and the Built Environment'), ('CAL', 'College of Acts and Letters'), ('CBA', 'College of Business Administration'), ('COC', 'College of Communication'), ('CCIS', 'College of Computer and Information Sciences'), ('COED', 'College of Education'), ('CE', 'College of Engineering'), ('CHK', 'College of Human Kinetics'), ('CL', 'College of Law'), ('CPSPA', 'College of Political Science and Public Administration'), ('CSSD', 'College of Social Sciences and Development'), ('CS', 'College of Science'), ('CTHTM', 'College of Tourism, Hospitality and Transportation Management')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identity',
            field=models.CharField(choices=[('Cisgender', 'Cisgender'), ('Transgender', 'Transgender'), ('Agender', 'Agender'), ('Gender Fluid', 'Gender Fluid'), ('Gender Queer', 'Gender Queer')], default='Cisgender', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_pronoun',
            field=models.CharField(choices=[('She/Her', 'She/Her'), ('He/Him', 'He/Him'), ('They/Them', 'They/Them'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Intersex', 'Intersex'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
