# Generated by Django 5.0.7 on 2024-08-09 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], max_length=20, null=True)),
                ('pronouns', models.CharField(blank=True, choices=[('he_him', 'He/Him'), ('she_her', 'She/Her'), ('they_them', 'They/Them'), ('other', 'Other')], max_length=20, null=True)),
                ('live_name', models.CharField(blank=True, max_length=255, null=True)),
                ('indigenous_cultural_community', models.BooleanField(default=False)),
                ('differently_abled_person', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
